export const env = {
  siteUrl: process.env.NEXT_PUBLIC_SITE_URL || "http://localhost:3000",
  sanityProjectId: process.env.NEXT_PUBLIC_SANITY_PROJECT_ID || "80lf2wvv",
  sanityDataset: process.env.NEXT_PUBLIC_SANITY_DATASET || "production",
  sanityApiVersion: process.env.NEXT_PUBLIC_SANITY_API_VERSION || "2025-01-01",
  smtpHost: process.env.SMTP_HOST || "smtp.hostinger.com",
  smtpPort: Number(process.env.SMTP_PORT || 465),
  helpEmailAddress: process.env.HELP_EMAIL_ADDRESS || "help@smahope.org",
  helpEmailPassword: process.env.HELP_EMAIL_PASSWORD || "",
  partnershipsEmailAddress: process.env.PARTNERSHIPS_EMAIL_ADDRESS || "partnerships@smahope.org",
  partnershipsEmailPassword: process.env.PARTNERSHIPS_EMAIL_PASSWORD || "",
  stripeSecretKey: process.env.STRIPE_SECRET_KEY || "",
  stripeBookPriceId: process.env.STRIPE_BOOK_PRICE_ID || "",
  stripeDonationPriceId: process.env.STRIPE_DONATION_PRICE_ID || "",
  paystackSecretKey: process.env.PAYSTACK_SECRET_KEY || "",
  paystackPublicKey: process.env.NEXT_PUBLIC_PAYSTACK_PUBLIC_KEY || "",
  paystackDonationSuccessUrl: process.env.PAYSTACK_DONATION_SUCCESS_URL || "/donate?status=success",
  paystackDonationCancelUrl: process.env.PAYSTACK_DONATION_CANCEL_URL || "/donate?status=cancelled",
  paystackDonationMonthlyPlanCode: process.env.PAYSTACK_DONATION_MONTHLY_PLAN_CODE || "",
  paystackDonationMonthlyPlanCodesNgn: process.env.PAYSTACK_DONATION_MONTHLY_PLAN_CODES_NGN || "",
  paystackDonationMonthlyPlanCodesUsd: process.env.PAYSTACK_DONATION_MONTHLY_PLAN_CODES_USD || "",
  paystackDonationNgnMin: Number(process.env.PAYSTACK_DONATION_NGN_MIN || 500),
  paystackDonationUsdMin: Number(process.env.PAYSTACK_DONATION_USD_MIN || 1),
  paystackBookSuccessUrl: process.env.PAYSTACK_BOOK_SUCCESS_URL || "/order-book?status=success",
  paystackBookCancelUrl: process.env.PAYSTACK_BOOK_CANCEL_URL || "/order-book?status=cancelled",
  paystackBookUnitPriceNgn: Number(process.env.PAYSTACK_BOOK_UNIT_PRICE_NGN || 15000),
  paystackBookDeliveryLagosNgn: Number(process.env.PAYSTACK_BOOK_DELIVERY_LAGOS_NGN || 0),
  paystackBookDeliveryOutsideLagosNgn: Number(process.env.PAYSTACK_BOOK_DELIVERY_OUTSIDE_LAGOS_NGN || 3000),
  flodeskApiKey: process.env.FLODESK_API_KEY || "",
  flodeskSegmentId: process.env.FLODESK_SEGMENT_ID || "",
};

export function hasSanityConfig() {
  return Boolean(env.sanityProjectId && env.sanityDataset);
}
